import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, locale }) {



  const messages = await getMessages();


  return (
    <html lang={locale}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextIntlClientProvider messages={messages}>
          <div className='container'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </NextIntlClientProvider>


      </body>
    </html>
  );
}
